name: science_lens
description: ScienceLens Flutter Web
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  file_picker: ^8.0.3
  image: ^4.1.7


flutter:
  uses-material-design: true
