name: Build & Deploy Flutter Web

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # 👉 This generates the missing web/ folder (index.html, etc.)
      - name: Ensure Flutter project skeleton (web)
        run: flutter create . --platforms=web --project-name science_lens

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Web (release)
        run: flutter build web --release \--dart-define=API_BASE=${{ secrets.API_BASE }} \--base-href="/science-lens-web/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
